# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fcc6f519ba38ea1bf29e67ffd813738788fd8db5da5ae34698db46628a6fe77bc9b5e0895501a8da0a3eadd76ea5f8f1c4ffc2476e1105e545fdb8c397b14f6a

test:
  secret_key_base: fe6a24c24392a86b8ee0eb3817dbcc6c82c2acc003f8c1b28098696a409c141539170a40b6ee33d3ba038acbe161bf241ac6eeb1858c49e87cbd4028a25907e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
